### ISSUE TITLE
Fix `shellcheck` violations and enable job in `pre-commit` configuration

### ISSUE THREAD

**Issue by myii** [opensourcewebsite-org/osw-devops#22]
**Is your feature request related to a problem? Please describe.**

As described in this comment: https://github.com/opensourcewebsite-org/osw-devops/pull/19#issuecomment-1150846105.

**Describe the solution you'd like**

The `shellcheck` violations should be fixed and then these lines can be uncommented:

https://github.com/opensourcewebsite-org/osw-devops/blob/2ac07e781a45e86d445c7fc93d291643d036ab34/.pre-commit-config.yaml#L16-L22

**Describe alternatives you've considered**

**Additional context**

**Comment by A1EF** [comment]
Fixed [here](https://github.com/opensourcewebsite-org/osw-devops/pull/29/files)
